export const state = () => ({
  all: [
    {
      id: 'ilzwo3wq',
      category: 'lead-adaptors',
      slug: 'ilink-blv-adaptor',
      name: 'ILINK-BLV Adaptor',
      short_name: 'ilinkBlv',
      short_description: 'Bifurcated Implantable Lead Adaptor',
      receptacle: 'IS-1 Bi or LV-1 Bi',
      connector: 'IS-1 Bi',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'ilz6uulc',
      category: 'lead-adaptors',
      slug: 'ilink-bis-adaptor',
      name: 'ILINK-BIS Adaptor',
      short_name: 'ilinkBis',
      short_description: 'Bifurcated Implantable Lead Adaptor',
      receptacle: ' 2 x IS-1 Bi',
      connector: ' IS-1 Bi',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'ilvajtgs',
      category: 'lead-adaptors',
      slug: '2xbis-bis-adaptor',
      name: '2XBIS/BIS Adaptor',
      short_name: 'adaptor2Xbis',
      short_description: 'Bifurcated Implantable Lead Adaptor',
      receptacle: '2 x IS-1 Bi',
      connector: 'IS-1 Bi',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'ilil3vtp',
      category: 'lead-adaptors',
      slug: 'b-is-adaptor',
      name: 'B/IS Adaptor',
      short_name: 'adaptorBiS',
      short_description: 'Bifurcated Implantable Lead Adaptors',
      receptacle: '2 x 5 mm Uni',
      connector: 'IS-1 Bi',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'il1zfubf',
      category: 'lead-adaptors',
      slug: 'bis-blv',
      name: 'BIS/BLV',
      short_name: 'adaptorBisBlv',
      short_description: 'Bipolar Implantable Lead Adaptor',
      receptacle: 'IS-1 Bi',
      connector: 'LV-1 Bi',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'ildlnxcd',
      category: 'lead-adaptors',
      slug: 'c-is-adaptor',
      name: 'C/IS Adaptor',
      short_name: 'adaptorCis',
      short_description: 'Unipolar Implantable Lead Adaptors',
      receptacle: '6 mm Uni',
      connector: 'IS-1 Uni',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'ilkqn7iv',
      category: 'lead-adaptors',
      slug: 'm-is-adaptor',
      name: 'M/IS Adaptor',
      short_name: 'adaptorMis',
      short_description: 'Unipolar Implantable Lead Adaptors',
      receptacle: '5 mm Uni',
      connector: 'IS-1 Uni',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'il9mibx3',
      category: 'lead-adaptors',
      slug: 'vv-plug',
      name: 'VV Plug',
      short_name: 'vvPlug',
      short_description: 'Implantable Lead Adaptor Connector Plugs',
      receptacle: 'N/A',
      connector: 'IS-1',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'il426wrw',
      category: 'lead-adaptors',
      slug: 'lv-1-plug',
      name: 'LV-1 Plug',
      short_name: 'lv1Plug',
      short_description: 'Implantable Lead Adaptor Connector Plugs',
      receptacle: 'N/A',
      connector: 'LV-1',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'ilhqp035',
      category: 'lead-adaptors',
      slug: 'blv-bis',
      name: 'BLV/BIS',
      short_name: 'blvBis',
      short_description: 'Bipolar Implantable Lead Adaptor',
      receptacle: 'LV-1 Bi',
      connector: 'IS-1 Bi',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'ilzgrmby',
      category: 'lead-adaptors',
      slug: 'bis-bis-extension',
      name: 'BIS/BIS Extension',
      short_name: 'bisBisExtension',
      short_description: 'Bipolar Implantable Lead Extension',
      receptacle: 'IS-1 Bi',
      connector: 'IS-1 Bi',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    },
    {
      id: 'il0ey1bi',
      category: 'lead-adaptors',
      slug: 'is4-df4-plug',
      name: 'IS4/DF4 Plug',
      short_name: 'is4Df4Plug',
      short_description: 'Implantable Lead Adaptor Connector Plugs',
      receptacle: 'N/A',
      connector: 'IS4/DF4',
      model: '',
      coil: '',
      insulation: '',
      length: ''
    }
  ]
})
